Dockerfile: add missing build dependencies for openssl-sys crate (#284)
Install perl and make before starting compilation, to avoid error:
error: failed to run custom build command for `openssl-sys v0.9.91`